---
- name: Configure proxy for apt
  ansible.builtin.template:
    src: "80proxy.j2"
    dest: /etc/apt/apt.conf.d/80proxy
    owner: root
    group: root
    mode: '0644'
  when: apt_proxy_enabled

- name: Unconfigure proxy for apt
  ansible.builtin.file:
    path: /etc/apt/apt.conf.d/80proxy
    state: absent
  when: not apt_proxy_enabled
