---
variables:
  IMAGE_ANSIBLE: jfxs/ansible
  IMAGE_DEFAULT: alpine:latest
  IMAGE_MARKDOWNLINT: davidanson/markdownlint-cli2
  IMAGE_NODE: node:lts-bullseye
  IMAGE_YAMLLINT: jfxs/ansible

stages:
  - checks
  - tests
  - gitlab-release
  - deploy

lint-file:
  image: $IMAGE_DEFAULT
  stage: checks
  before_script:
    - apk --no-cache add curl file git ncurses
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
    - task --version
    - curl --progress-bar -o Taskfile.yml https://gitlab.com/op_so/task/task-templates/-/raw/main/Taskfile.dist.yml
    - task 00:00-init-task
  script:
    - task lint:file
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"

lint-markdown:
  image:
    name: $IMAGE_MARKDOWNLINT
    entrypoint: [""]
  stage: checks
  before_script:
    - export PATH="$PATH:./bin"
    - sh -c "$(wget -qO - https://taskfile.dev/install.sh)" -- -d
    - task --version
    - wget -qO Taskfile.yml https://gitlab.com/op_so/task/task-templates/-/raw/main/Taskfile.dist.yml
    - task 00:00-init-task
  script:
    - task lint:markdown G="\"**/*.md\" \"#node_modules\" \"#.node_cache\""
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"

lint-yaml:
  image: $IMAGE_YAMLLINT
  stage: checks
  before_script:
    - export PATH="$PATH:./bin"
    - sh -c "$(wget -qO - https://taskfile.dev/install.sh)" -- -d
    - task --version
    - wget -qO Taskfile.yml https://gitlab.com/op_so/task/task-templates/-/raw/main/Taskfile.dist.yml
    - task 00:00-init-task
  script:
    - task lint:yaml
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"

test-ansible:
  image: $IMAGE_ANSIBLE
  stage: tests
  before_script:
    - export PATH="$PATH:./bin"
    - sh -c "$(wget -qO - https://taskfile.dev/install.sh)" -- -d
    - task --version
    - wget -qO Taskfile.yml https://gitlab.com/op_so/task/task-templates/-/raw/main/Taskfile.dist.yml
    - task 00:00-init-task
  script:
    - task 00:10-ansible-test-local
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"

gitlab-release:
  retry: 2
  image: $IMAGE_NODE
  stage: gitlab-release
  before_script:
    - yarn install
  script:
    - npx semantic-release
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
