---
- name: Update
  ansible.builtin.apt:
    update-cache: true
  changed_when: false

- name: Upgrade and cleanup
  ansible.builtin.apt:
    upgrade: dist
    autoclean: true
    autoremove: true

- name: Install system packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - software-properties-common
    state: latest
