---
- name: Update
  ansible.builtin.apt:
    update-cache: true
  changed_when: false

- name: Upgrade
  ansible.builtin.apt:
    upgrade: dist

- name: Install system packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - software-properties-common
    state: latest

- name: Cleanup
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
  changed_when: false
