---
- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_file

- name: Reboot server
  ansible.builtin.reboot:
    reboot_timeout: "{{ reboot_timeout }}"
  when: reboot_file.stat.exists or reboot_force
